### ISSUE TITLE
error after installation, thank you! 

### ISSUE THREAD

**Issue by TeleViaBox** [Khateebxtreme/Youtube_Lite#1]
This error message shown on my browser after installation and running this repo:

```
/home/user001/Documents/practice/youtube-clone/Youtube_Lite/src/utils/fetchFromAPI.jsx:3:19
1  |  import axios from "axios";
2  |  const BASE_URL = "https://youtube-v31.p.rapidapi.com";
3  |  import config from "./config";
   |                      ^
4  |  let ordering = ["date", "relevance", "rating", "title", "viewCount"];
5  |  let index = Math.floor(Math.random() * ordering.length);
    at formatError (file:///home/user001/Documents/practice/youtube-clone/Youtube_Lite/node_modules/vite/dist/node/chunks/dep-79892de8.js:43113:46)
    at TransformContext.error (file:///home/user001/Documents/practice/youtube-clone/Youtube_Lite/node_modules/vite/dist/node/chunks/dep-79892de8.js:43109:19)
    at normalizeUrl (file:///home/user001/Documents/practice/youtube-clone/Youtube_Lite/node_modules/vite/dist/node/chunks/dep-79892de8.js:41378:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.transform (file:///home/user001/Documents/practice/youtube-clone/Youtube_Lite/node_modules/vite/dist/node/chunks/dep-79892de8.js:41512:47)
    at async Object.transform (file:///home/user001/Documents/practice/youtube-clone/Youtube_Lite/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:30)
    at async loadAndTransform (file:///home/user001/Documents/practice/youtube-clone/Youtube_Lite/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

**Comment by TeleViaBox** [comment]
FYI, 
After I commanded, I run into this error:

```
Run_Locally
Clone the project

  $ git clone https://github.com/Khateebxtreme/Youtube_Lite
Go to the project directory

  cd Youtube_Lite
Install dependencies

  npm install
Start the server

  npm run dev
```

**Comment by Khateebxtreme** [comment]
Sorry for not mentioning it here but the config file is something you will have to create on your own to hold your rapid api key which you will get when you sign up with rapid api and subscribe to the Youtube-v3 API.
